FROM python:3.12.13-slim

WORKDIR /app

COPY requirements.graphql.txt .
RUN pip install --no-cache-dir -r requirements.graphql.txt \
    && opentelemetry-bootstrap -a install

COPY api-graphql-mcp.py .

ARG API_MCP_BASE_URL
ARG API_MCP_SERVER_NAME

ENV API_MCP_BASE_URL=${API_MCP_BASE_URL}
ENV API_MCP_SERVER_NAME=${API_MCP_SERVER_NAME}

EXPOSE 443

CMD ["opentelemetry-instrument", "python", "api-graphql-mcp.py"]
